include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 🔧 Основные улучшения кода
    prefer_const_constructors: true         # Использовать const, где это возможно
    prefer_final_locals: true               # Локальные переменные по возможности final
    avoid_print: true                       # Не использовать print (использовать логгер)
    unnecessary_this: true                  # Убрать лишние this, если они не нужны
    avoid_unnecessary_containers: true      # Не использовать Container без параметров

    # 📐 Упорядоченность и читаемость
    sort_constructors_first: true           # Конструкторы всегда в начале класса
    sort_unnamed_constructors_first: true   # Безымянные конструкторы выше именованных

    # 🧱 Безопасность и читаемость API
    always_declare_return_types: true       # Всегда указывать возвращаемый тип функций
    use_key_in_widget_constructors: true    # Добавлять super.key в конструкторы виджетов

    # ✨ По вкусу — можно добавить
    prefer_const_literals_to_create_immutables: true  # Использовать const для неизменяемых списков, map, set