workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
