name: VOX
description: The Vox Walkers Mobile Application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.2+10

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  auto_route: 10.0.1
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: 11.4.0 
  dio: ^5.4.3+1

  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic_plus: ^3.4.0
  flutter_riverpod: 2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: 3.0.0
  image_picker: 1.1.2
  intl: 0.20.2
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  riverpod_annotation: 2.6.1
  smooth_page_indicator: 1.2.1
  url_launcher: 6.3.1
  mask_text_input_formatter: 2.9.0
  shared_preferences: 2.5.3
  flutter_inset_shadow: 2.0.3
  permission_handler: 12.0.0+1
  geolocator: 14.0.0
  analyzer: 7.3.0
  vox_ui_kit:
    path: /Volumes/External/projects/ui_kit
  vox_uikit:
    path: /Volumes/External/test_projects/vox_uikit 
  package_info_plus: ^8.3.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.0.4
  json_serializable: ^6.8.0
  riverpod_generator: 2.6.5
  auto_route_generator: 10.0.1
  build_runner: 2.4.15
  custom_lint:
  riverpod_lint: 2.6.5
  golden_toolkit: ^0.15.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/vox_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/arrow-left.png
    - assets/3d_sticker.png
    - assets/edit_icon.png
    - assets/navigation.png
    - assets/calendar.png
