name: vox_ui_kit
description: "Vox apps ui kit"
version: 0.0.15

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: 4.5.2
  flutter_inset_shadow: 2.0.3
  flutter_localizations:
    sdk: flutter
  geolocator: 14.0.0
  screenshot: ^3.0.0
  slang: 4.6.1
  slang_flutter: 4.6.0
  yandex_maps_mapkit: 4.15.0-beta

dev_dependencies:
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  slang_build_runner: 4.6.0 
  test: 1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/auth/flags/
    - assets/images/blog/
    - assets/images/onboarding/
    - assets/images/services/
    - assets/images/socials/
    - assets/images/temp/
    
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-Medium.ttf
          weight: 500
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-SemiBold.ttf
          weight: 600
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-Light.ttf
          weight: 300
